image: python:3.11

stages:
  - test
  - deploy

before_script:
  # Install SSH client and other dependencies you might need
  - apt-get update -yqq
  - apt-get install -yqq sshpass

test:
  stage: test
  script:
    - pip install -r requirements.txt  # Install dependencies
    - pytest  # run unit tests

variables:
  REMOTE_SERVER: "ljthey.co.uk"
  REMOTE_USER: "ice"
  SSH_PASSWORD: "$CI_SSH_PASSWORD"
  DEPLOY_DIRECTORY: "IceBreaker/flask"
  APP_MODULE: "flask_app:app"
  # production port
  GUNICORN_PORT: 8000
  

deploy:
  stage: deploy
  script:
    # Search for existing pid on port
    - EXISTING_PID=$(sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "lsof -i :$GUNICORN_PORT -t || echo 'not_found'")
    - echo "Checking for existing process on port $GUNICORN_PORT"
    - echo "EXISTING_PID $EXISTING_PID"
        # Extract the first PID from the list
    - FIRST_PID=$(echo "$EXISTING_PID" | head -n 1)

    # Kill the first PID if it's not "not_found"
    - >
      if [ "$FIRST_PID" != "not_found" ]; then
        echo "Killing existing process on port $GUNICORN_PORT with PID $FIRST_PID"
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "kill $FIRST_PID"
      else
        echo "No existing process found on port $GUNICORN_PORT"
      fi

    # make dir and copy files
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "mkdir -p $DEPLOY_DIRECTORY"
    - sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* "$REMOTE_USER@$REMOTE_SERVER:$DEPLOY_DIRECTORY"
    # # - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "cd $DEPLOY_DIRECTORY && pip install -r requirements.txt"
    # - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "cd $DEPLOY_DIRECTORY && nohup gunicorn --workers 2 --bind 0.0.0.0:$GUNICORN_PORT $APP_MODULE"

    # launch - there is issue with running
    # - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "export PATH=\$PATH:/home/ice/.local/bin && cd $DEPLOY_DIRECTORY && nohup gunicorn --workers 2 --bind 0.0.0.0:$GUNICORN_PORT $APP_MODULE &>/dev/null & < /dev/null &"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "export PATH=\$PATH:/home/ice/.local/bin && cd $DEPLOY_DIRECTORY && nohup ./service.sh &>/dev/null  &"

    - sleep 5

    # Show current pid
    - echo $(sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "lsof -i :$GUNICORN_PORT -t || echo 'not_found'")

  only:
    - master
