
users = [
    {"userID": "A", "firstName": "UserA", "city": "New York", "country": "USA", "favActivity": "playing basketball",
     "favFood": "chocolate cake", "feeling": "happy"},
    {"userID": "B", "firstName": "UserB", "city": "Los Angeles", "country": "USA", "favActivity": "swimming",
     "favFood": "sushi", "feeling": "excited"},
    {"userID": "C", "firstName": "UserC", "city": "Chicago", "country": "USA", "favActivity": "running",
     "favFood": "salad", "feeling": "content"},
    {"userID": "D", "firstName": "UserD", "city": "New York", "country": "USA", "favActivity": "playing basketball",
     "favFood": "pizza", "feeling": "happy"},
    {"userID": "E", "firstName": "UserE", "city": "Boston", "country": "USA", "favActivity": "cycling",
     "favFood": "chocolate cake", "feeling": "joyful"},
    {"userID": "F", "firstName": "UserF", "city": "San Francisco", "country": "USA", "favActivity": "hiking",
     "favFood": "burrito", "feeling": "adventurous"},
    {"userID": "G", "firstName": "UserG", "city": "New York", "country": "USA", "favActivity": "jogging",
     "favFood": "salad", "feeling": "good"},
    {"userID": "H", "firstName": "UserH", "city": "Tokyo", "country": "Japan", "favActivity": "swimming",
     "favFood": "sushi", "feeling": "excited"},
    {"userID": "I", "firstName": "UserI", "city": "Kyoto", "country": "Japan", "favActivity": "meditating",
     "favFood": "matcha cake", "feeling": "peaceful"},
    {"userID": "J", "firstName": "UserJ", "city": "London", "country": "UK", "favActivity": "watching football",
     "favFood": "fish and chips", "feeling": "energetic"},
    {"userID": "K", "firstName": "UserK", "city": "london", "country": "United Kingdom",
     "favActivity": "watching football", "favFood": "fish and chips", "feeling": "excied"},
    {"userID": "L", "firstName": "UserL", "city": "Shenzhen", "country": "China", "favActivity": "violin",
     "favFood": "chocolate", "feeling": "tired"},
    {"userID": "M", "firstName": "UserM", "city": "Beijing", "country": "CHINA", "favActivity": "piano",
     "favFood": "Dumplings", "feeling": "sad"},
    {"userID": "N", "firstName": "UserN", "city": "Cambridge", "country": "UK", "favActivity": "cook",
     "favFood": "Tart", "feeling": "ok"},
    {"userID": "O", "firstName": "UserO", "city": "Oxford", "country": "uk", "favActivity": "baking", "favFood": "Rice",
     "feeling": "fine"},
    {"userID": "P", "firstName": "UserP", "city": "shanghai", "country": "china", "favActivity": "reading",
     "favFood": "Burger", "feeling": "crying"},
    # Add more users if needed
]
